export const ActionTypes = {
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    FETCH_CATEGORIES: "FETCH_CATEGORIES",
    FETCH_PRODUCTSBY_CATEGORY: "FETCH_PRODUCTSBY_CATEGORY",
    SEARCH_PRODUCTS: "SEARCH_PRODUCTS",
    ADD_TO_CART: "ADD_TO_CART"
};